apiVersion: v1
kind: Service
metadata:
  name: devsecops-incident-platform
  namespace: devsecops-platform
  labels:
    app: devsecops-incident-platform
    monitoring: enabled
spec:
  selector:
    app: devsecops-incident-platform
  ports:
    - name: http
      port: 80
      targetPort: 8000
