apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devsecops-incident-platform
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - devsecops-platform
  selector:
    matchLabels:
      app: devsecops-incident-platform
      monitoring: enabled
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s

