apiVersion: v1
kind: Secret
metadata:
  name: incident-platform-secrets
  namespace: devsecops-platform
type: Opaque
stringData:
  POSTGRES_DB: incident_db
  POSTGRES_USER: incident_user
  POSTGRES_PASSWORD: change_me
  DATABASE_URL: postgresql+psycopg://incident_user:change_me@incident-postgres:5432/incident_db

